### ISSUE TITLE
Unit test

### ISSUE THREAD

**Issue by JeremieLapert** [lagoshny/ngx-hateoas-client#28]
Hi,
many thanks for your library, it's a good job.

I have a problem when i want test my Service.

Have you ever seen the following behavior? 

thank you in advance for your help 

Service Code
```
@Injectable({
  providedIn: 'root'
})
export class CodeService extends HateoasResourceOperation<Code> {
  constructor() {
    super(Code);
  }
}
```

Service Code Test
```
import { SpectatorService } from '@ngneat/spectator';
import { createServiceFactory } from '@ngneat/spectator/jest';
import { CodeService } from './code.service';

describe('CodeServiceService', () => {
  let spectator: SpectatorService<CodeService>;
  const createService = createServiceFactory({
    service: CodeService
  });

  beforeEach(() => {
    spectator = createService();
  });
  it('should be created', () => {
    expect(spectator.service).toBeTruthy();
  });
});
```

Error message
```

Error: You need initialize Injector
    at Function.get (/home/jlapert/Documents/Sources/customer/refclearing/node_modules/@lagoshny/ngx-hateoas-client/fesm2015/lagoshny-ngx-hateoas-client.mjs:19:15)
    at new HateoasResourceOperation (/home/jlapert/Documents/Sources/customer/refclearing/node_modules/@lagoshny/ngx-hateoas-client/fesm2015/lagoshny-ngx-hateoas-client.mjs:2377:58)
    at new CodeService (/home/jlapert/Documents/Sources/customer/refclearing/src/app/services/code.service.ts:10:5)
    at Object.CodeService_Factory [as factory] (ng:///CodeService/ɵfac.js:5:10)
    at R3Injector.hydrate (/home/jlapert/Documents/Sources/customer/refclearing/node_modules/@angular/core/fesm2015/core.mjs:11443:35)
    at R3Injector.get (/home/jlapert/Documents/Sources/customer/refclearing/node_modules/@angular/core/fesm2015/core.mjs:11259:33)
    at NgModuleRef.get (/home/jlapert/Documents/Sources/customer/refclearing/node_modules/@angular/core/fesm2015/core.mjs:21821:33)
    at TestBedRender3.inject (/home/jlapert/Documents/Sources/customer/refclearing/node_modules/@angular/core/fesm2015/testing.mjs:1713:52)
    at Function.inject (/home/jlapert/Documents/Sources/customer/refclearing/node_modules/@angular/core/fesm2015/testing.mjs:1609:37)
    at /home/jlapert/Documents/Sources/customer/refclearing/node_modules/@ngneat/spectator/fesm2015/ngneat-spectator.mjs:1691:62
    at /home/jlapert/Documents/Sources/customer/refclearing/src/app/services/code.service.spec.ts:12:17
    at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (/home/jlapert/Documents/Sources/customer/refclearing/node_modules/zone.js/bundles/zone-testing-bundle.umd.js:407:30)
    at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (/home/jlapert/Documents/Sources/customer/refclearing/node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3765:43)
    at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (/home/jlapert/Documents/Sources/customer/refclearing/node_modules/zone.js/bundles/zone-testing-bundle.umd.js:406:56)
    at Zone.Object.<anonymous>.Zone.run (/home/jlapert/Documents/Sources/customer/refclearing/node_modules/zone.js/bundles/zone-testing-bundle.umd.js:167:47)
    at Object.wrappedFunc (/home/jlapert/Documents/Sources/customer/refclearing/node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4250:34)
    at Promise.then.completed (/home/jlapert/Documents/Sources/customer/refclearing/node_modules/jest-circus/build/utils.js:391:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/home/jlapert/Documents/Sources/customer/refclearing/node_modules/jest-circus/build/utils.js:316:10)
    at _callCircusHook (/home/jlapert/Documents/Sources/customer/refclearing/node_modules/jest-circus/build/run.js:181:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at _runTest (/home/jlapert/Documents/Sources/customer/refclearing/node_modules/jest-circus/build/run.js:148:5)
    at _runTestsForDescribeBlock (/home/jlapert/Documents/Sources/customer/refclearing/node_modules/jest-circus/build/run.js:66:9)
    at _runTestsForDescribeBlock (/home/jlapert/Documents/Sources/customer/refclearing/node_modules/jest-circus/build/run.js:60:9)
    at run (/home/jlapert/Documents/Sources/customer/refclearing/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/home/jlapert/Documents/Sources/customer/refclearing/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:170:21)
```

**Comment by lagoshny** [comment]
Hi @JeremieLapert ,

I have added possibility for use the lib in the `TestBed` or `Spectator`, in briefly you need to import `NgxHateoasClientModule.forRoot()` module in the test.

For more details, see [testing documentation](https://github.com/lagoshny/ngx-hateoas-client/tree/master#Testing)

These changes were published in `3.0.5` lib version for Angular >=12 and `2.3.5` for Angular <= 12.

**Comment by JeremieLapert** [comment]
@lagoshny : Thank you very much for the answer. It's perfect, it works!

**Comment by voloKh28** [comment]
Hi @lagoshny

Is it possible to use a jest as a testing framework? If yes, then do I need some specific configuration for it?

Thank you in advance.

**Comment by lagoshny** [comment]
Hi @voloKh28 , 
I have not used jest. It is more question about using jest with angular. I think it is possible.
If you have some examples with problems, you can write it and I will try to help you.

**Comment by voloKh28** [comment]
> Hi @voloKh28 , I have not used jest. It is more question about using jest with angular. I think it is possible. If you have some examples with problems, you can write it and I will try to help you.

I had an issue with running tests with Jest cause of some wrong Jest config I think. The error looked like this:

`  /Users/v.khmil/Documents/dbh-config-service-frontend/node_modules/uri-templates-es/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export { UriTemplate } from './lib/uri-template';
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | import { Injectable } from '@angular/core';
    > 2 | import { HateoasResourceOperation, HateoasResourceService, ResourceCollection } from '@lagoshny/ngx-hateoas-client';
        | ^`
        
So I was trying to fix this issue by updating the `jest.config.ts`, I have tried many options, and one of them was this one:

`transformIgnorePatterns: [
    'node_modules/(?!(uri-templates-es)/)',
  ],`
  
 which, I thought, would work fine, but I had the same issue over and over. Then my teammate tried to update `jest.config.ts` with the following changes:
 
`const esModules = ['.*\\.mjs$', ''].join('|');`

an then use this variable in `transformIgnorePatterns`:

`transformIgnorePatterns: [`node_modules/(?!${esModules})`],`

Only with these changes for `jest.config.ts` the tests were running file and without errors.

**Comment by lagoshny** [comment]
Yes, there is a problem in difference between CommonJS and ES modules.
Jest uses NodeJs syntax CommonJS modules, but Angular uses ES modules.

I think your solution is one of the proper way, because after some googling people bring the same solutions:

https://jestjs.io/docs/ecmascript-modules
https://stackoverflow.com/questions/35756479/does-jest-support-es6-import-export
https://fireflysemantics.medium.com/unit-testing-your-angular-library-project-with-jest-42429a8716eb
